@startuml

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods
hide empty members

class MultipleGeneration extends Generation implements GenerationStrategy{
+ <<Create>> MultipleGeneration(file : File, savePath : String)
+  generate(file : File, savePath : String) 
+  write(file : File, savePath : String) 
}

MultipleGeneration --> FileWriter : "1\n#ecriture"
MultipleGeneration --> FileWriter : "1\n#ecriture"


@enduml
